// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as physics$0 from "../physics/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AskOllama(prompt: string): $CancellablePromise<$models.OllamaResponse | null> {
    return $Call.ByID(2478993148, prompt);
}

export function EndCustomDrag(vx: number, vy: number): $CancellablePromise<void> {
    return $Call.ByID(3978924935, vx, vy);
}

export function MoveCustomDrag(x: number, y: number, vx: number, vy: number): $CancellablePromise<void> {
    return $Call.ByID(1550424949, x, y, vx, vy);
}

export function SetPhysics(phy: physics$0.Engine | null): $CancellablePromise<void> {
    return $Call.ByID(1452700448, phy);
}

export function StartCustomDrag(): $CancellablePromise<void> {
    return $Call.ByID(2535004518);
}
